apiVersion: apps/v1
kind: Deployment
metadata:
  name: CHANGE_ME_APP_NAME
  namespace: CHANGE_ME_NAMESPACE
  labels:
    app: CHANGE_ME_APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CHANGE_ME_APP_NAME
  template:
    metadata:
      labels:
        app: CHANGE_ME_APP_NAME
    spec:
      imagePullSecrets:
        - name: dockerhub-regcred
      containers:
        - name: CHANGE_ME_APP_NAME
          image: CHANGE_ME_IMAGE:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: CHANGE_ME_APP_NAME
  namespace: CHANGE_ME_NAMESPACE
  labels:
    app: CHANGE_ME_APP_NAME
spec:
  selector:
    app: CHANGE_ME_APP_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP