apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 6.11.0
    chart: argo-cd
    helm:
      values: |
        server:
          extraArgs:
            - --insecure # Since we're using Cloudflare for TLS
          config:
            url: https://argocd.shinyshiba.com
            application.instanceLabelKey: argocd.argoproj.io/instance
        configs:
          params:
            server.insecure: true # Since we're using Cloudflare for TLS
        redis-ha:
          enabled: false # Single node setup
        controller:
          replicas: 1
        server:
          replicas: 1
        repoServer:
          replicas: 1
        applicationSet:
          replicas: 1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
