apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    path: apps
    repoURL: 'https://github.com/hojhon/homelab-argocd'
    targetRevision: main
    directory:
      recurse: true
      include: argocd-cloudflared.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudflare
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

