apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/hojhon/homelab-argocd.git'
    targetRevision: main
    path: apps/cloudflared-consolidated
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
