apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hojhon/homelab-argocd.git'
    path: apps
    directory:
      recurse: true
      # Exclude raw resource manifests (Deployment/Service/etc) so the root app doesn't
      # claim the same resources as child applications. Keep Application CRs in the
      # repo (e.g. apps/*/application.yaml) and exclude the typical resource filenames.
      exclude:
        - "**/*deployment*.yaml"
        - "**/*deployment*.yml"
        - "**/*service*.yaml"
        - "**/*service*.yml"
        - "**/*.disabled"
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
