apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://helm.releases.hashicorp.com"
    chart: vault
    targetRevision: 0.31.0
    helm:
      values: |
        server:
          # expose Vault via NodePort for LAN access (temporary)
          service:
            type: NodePort
            nodePort: 32000
          # extraEnvironmentVars must be an object/map per chart schema
          extraEnvironmentVars:
            VAULT_DEV_ROOT_TOKEN_ID: "root"
          # Keep Vault running across pod restarts by enabling persistent data storage
          standalone:
            enabled: true
          dataStorage:
            enabled: true
            # small default PVC settings (can be customized later)
            storageClass: ""
            accessMode: ReadWriteOnce
            size: 1Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
