name: 2 - Deploy Applications

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main
    paths:
      - 'apps/**'

jobs:
  deploy:
    runs-on: [self-hosted, dev-ops]
    environment: homelab-variables
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        run: |
          if [ -f "/home/github-runner/.kube/config" ]; then
            echo "KUBECONFIG=/home/github-runner/.kube/config" >> $GITHUB_ENV
          elif [ -f "/etc/rancher/k3s/k3s.yaml" ]; then
            cp /etc/rancher/k3s/k3s.yaml kubeconfig.yaml
            chmod 600 kubeconfig.yaml
            echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV
          else
            echo "No kubeconfig found on runner" >&2
            exit 1
          fi

      - name: Apply Application Manifests
        run: |
          echo "Applying ArgoCD application manifest..."
          kubectl --kubeconfig="$KUBECONFIG" apply --validate=false -f apps/argocd.yaml
          
          echo "Applying Cloudflared application manifest..."
          kubectl --kubeconfig="$KUBECONFIG" apply --validate=false -f apps/cloudflared.yaml

      - name: Clean up
        if: always()
        run: rm -f kubeconfig.yaml || true