name: Deploy ArgoCD

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy:
    runs-on: dev-ops
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Create namespaces
        run: |
          kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace cloudflare --dry-run=client -o yaml | kubectl apply -f -

      - name: Create ArgoCD admin password
        run: |
          kubectl -n argocd create secret generic argocd-secret \
            --from-literal=admin.password="${{ secrets.ARGOCD_ADMIN_PASSWORD }}" \
            --from-literal=admin.passwordMtime="$(date +%FT%T%Z)" \
            --dry-run=client -o yaml | \
            kubectl apply --validate=false -f -

      - name: Create Cloudflared tunnel token
        run: |
          kubectl -n cloudflare create secret generic cloudflared-cloudflare-tunnel-remote \
            --from-literal=tunnelToken="${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}" \
            --dry-run=client -o yaml | \
            kubectl apply --validate=false -f -

      - name: Apply ArgoCD
        run: |
          kubectl apply --validate=false -f apps/argocd.yaml
          kubectl -n argocd wait --timeout=60s --for=condition=established crd/applications.argoproj.io || true

      - name: Wait for ArgoCD to be ready
        run: |
          kubectl -n argocd wait --for=condition=available --timeout=300s deployment/argocd-server || true
          sleep 30  # Give additional time for services to stabilize

      - name: Apply Cloudflared
        run: kubectl apply --validate=false -f apps/cloudflared.yaml

      - name: Clean up
        if: always()
        run: rm -f kubeconfig.yaml