apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflare
    labels:
        app.kubernetes.io/managed-by: argocd
stringData:
    token: ENC[AES256_GCM,data:JiQ64NOmfPBdO8iQU1xiFNVzkw5/rA1Mbq5gkEFsDkSGufcSiO15yNwXlvIaCCCwAVQ+qQOGeeHJblNZePxd5T9H/FEHh8/WV7wEGfJJOE1p+/t3OCVVruSdp0XsP7SWEUpktAm6uMj68JBZH0mZotZuyz1uvTEgwt34GpRRGuqymCTPTpZ/KBbM5YS2RiBGQ7+HOXidlayWlCK6dg7qAtu2E21IG6wKq6hDo4c4zP6/dezOHnZ1IA==,iv:lF4ul8WMZpnxn6LBbmELC/1IN+skA65H/trXSE5TNZ0=,tag:yBdBHbAp0ZorZSD8lX0hnQ==,type:str]
sops:
    lastmodified: "2025-09-27T05:33:42Z"
    mac: ENC[AES256_GCM,data:rLlybbY6Gdq1MBxLz3LYHOk8zVG7gXLUOVEV9GmKRv08TwQ4/UqEnwpG45XYXqrR4AhLnBTQB34ZeEOgZ+KuiU1QfOXElQiYZ5tATqp3ICb+aG/63iMkF7qizfFTGdiKz74p4QjniO8z7S6qXnyzExDhm6dt68EUE1NUY+Dxpvs=,iv:6ReXo6aGHzVgUMYtvPgIxS/HZNbH7oMwjm/8Uypbx9o=,tag:4rNNqH5ipOiylh+JdWHY9g==,type:str]
    pgp:
        - created_at: "2025-09-27T05:33:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdFGnwR2eLMISAQdAI5xDhESHBT7mfXJBbrjFi5HyZ2BKGN5Wz58DKaq5GAgw
            ePPkvbP796fEVGXHxm+og1jQA3cLHBKfci7NFZJKHjDTLmOEe/WLvsJti7SHoDcH
            1GgBCQIQYFYQtgl6HhhdnL8TCI8fotAT6iELqjpK3KZVt5rWJ+vQS2xI2as9fIUZ
            mXlurS6YOH0ETb7nU/3gwNVNI+WnoZtx4L/go/tCK1HGBPxJYlDS9PpZYw1E0h8n
            XdnopVG4wmVxJg==
            =FAyp
            -----END PGP MESSAGE-----
          fp: C9FAA9F1749F06E36E8CD118C8641C78CDE2786B
    unencrypted_suffix: _unencrypted
    version: 3.10.2